// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaiQRYmPwvCVR33bOuzJ5aAbH5VEtsmY0',
    appId: '1:445533770554:web:b45e2d6c87e6d4ae977603',
    messagingSenderId: '445533770554',
    projectId: 'datatest-7a989',
    authDomain: 'datatest-7a989.firebaseapp.com',
    databaseURL: 'https://datatest-7a989-default-rtdb.firebaseio.com',
    storageBucket: 'datatest-7a989.appspot.com',
    measurementId: 'G-63VDNLV1XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTlEUbQfVWTWSWKb82539O6ewHyH4HYd0',
    appId: '1:445533770554:android:9aa90fc4616dd6cb977603',
    messagingSenderId: '445533770554',
    projectId: 'datatest-7a989',
    databaseURL: 'https://datatest-7a989-default-rtdb.firebaseio.com',
    storageBucket: 'datatest-7a989.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdzmW6-9390BUhk_s9kwP4MUQZbj8W84k',
    appId: '1:445533770554:ios:52d073f295653010977603',
    messagingSenderId: '445533770554',
    projectId: 'datatest-7a989',
    databaseURL: 'https://datatest-7a989-default-rtdb.firebaseio.com',
    storageBucket: 'datatest-7a989.appspot.com',
    iosBundleId: 'com.example.test.test1',
  );
}
